
https://backoffice.ct075nck5-franketec1-p1-public.model-t.cc.commerce.ondemand.com/odata2webservices/InboundFrankeProductThumbnail/Products?$filter=catalogVersion/integrationKey%20eq%20%27Staged%7CDefault%27&$skip=0&$top=3&$expand=thumbnail
Authorization: Basic admin J&)zs{7;wgkV5L=et+&68t{~8